// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChjZn3nIeUC3Py7f7gBnjlXSkNuDTine0',
    appId: '1:875621309287:web:b4e77807b9db679566adc2',
    messagingSenderId: '875621309287',
    projectId: 'twitch-kian',
    authDomain: 'twitch-kian.firebaseapp.com',
    storageBucket: 'twitch-kian.appspot.com',
    measurementId: 'G-YTFFC73XWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcWeYHYHt_NLCcZlvZrAqBaQtBgRO5YZ8',
    appId: '1:875621309287:android:2c1dcdeaf32d70f766adc2',
    messagingSenderId: '875621309287',
    projectId: 'twitch-kian',
    storageBucket: 'twitch-kian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4yM56e4oYRTkgRim-9ocKIfqLFJnSL5k',
    appId: '1:875621309287:ios:fd8319f4b698a7d766adc2',
    messagingSenderId: '875621309287',
    projectId: 'twitch-kian',
    storageBucket: 'twitch-kian.appspot.com',
    iosClientId: '875621309287-r6f44pmab5lqj125c4a3runisosomg8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitchClone',
  );
}
